// <auto-generated />
using GetOnIt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GetOnIt.Data.GOIMigrations
{
    [DbContext(typeof(GetOnItContext))]
    partial class GetOnItContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.17");
#pragma warning restore 612, 618
        }
    }
}
